title: Barnyard Organics
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Local and organic! Real, good ingredients. No weird stuff. Custom Roasting. Bio-Ag Distributor. General Seed Distributor. Grain Cleaning & Drying.
# baseurl: "/barnyard-organics"
url: "www.barnyardorganics.com" # the base hostname & protocol for your site, e.g. http://example.com

permalink: pretty

collections:
  feed-products:
    output: true
    permalink: "/feed/:path/"
  pages:
    output: true
    permalink: "/:path/"

# Build settings
markdown: kramdown
# theme: minima
gems:
  - jekyll-menus
  - jekyll-babel
exclude:
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed

google_analytics: UA-39666952-8

source: source
include: [/faq.md]
